acm/urls.py
from . import views
from django.conf.urls import url

urlpatterns = [
    # Product
    url(r'^admins/$', views.AdminList.as_view(), name='admin-list'),
]

prd/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import never_cache

from . import views

urlpatterns = [
    # Product
    url(r'^product-list/$', views.ProductList.as_view(), name='product-list'),
    url(r'^product-detail/(?P<pk>[0-9]+)/$', never_cache(views.ProductDetail.as_view()), name='product-detail'),
    url(r'^product-add/$', login_required(views.CreateProduct.as_view()), name='product-create'),
    url(r'^product-update/(?P<pk>[0-9]+)/$', login_required(views.UpdateProduct.as_view()), name='product-update'),
    url(r'^product-delete/(?P<pk>[0-9]+)/$', login_required(views.DeleteProduct.as_view()), name='product-delete'),
    url(r'^restapi/(?P<product>[\w-]+)/$', views.rest_product, name='product-restapi'),
    # Release
    url(r'^release-list/$', never_cache(views.ReleaseList.as_view()), name='release-list'),
    url(r'^release-detail/$', never_cache(views.ReleaseDetail.as_view()), name='release-detail'),
    url(r'^release/([\w-]+)/$', never_cache(views.ProductReleaseList.as_view()), name='release-list-by-product'),
    url(r'^release-create/(?P<product>[\w-]+)/$', never_cache(login_required(views.ReleaseCreate.as_view())),
        name='release-create'),
    url(r'^release-issue/(?P<pk>[0-9]+)/$', login_required(views.release_issue), name='release-issue'),
    # Release part
    url(r'^releasepart-add/(?P<product>[\w-]+)$', views.ReleasePartCreate.as_view(), name='releasepart-create'),
    url(r'^releasepart-update/(?P<pk>[0-9]+)/$', login_required(views.ReleasePartUpdate.as_view()),
        name='releasepart-update'),
    url(r'^releasepart-delete/(?P<pk>[0-9]+)/$', login_required(views.ReleasePartDelete.as_view()),
        name='releasepart-delete'),
    # Build
    url(r'^build/(?P<pk>[0-9]+)/$', views.ReleaseBuildList.as_view(), name='build-list-by-release'),
    url(r'^build-create/([\w-]+)/$', views.create_build, name='build-create'),
    url(r'^build-detail/(?P<pk>[0-9]+)/$', views.BuildDetail.as_view(), name='build-detail'),
    url(r'^build-list$', views.BuildList.as_view(), name='build-list'),
    # url(r'release/feeds/builds/(?P<release_id>[0-9]+)/$', views.feeds_build),
    # Hotfix
    url(r'hotfix-list$', views.HotFixList.as_view(), name='hotfix-list'),
    url(r'hotfix-create/(?P<pk>[0-9]+)/$', login_required(views.HotFixCreate.as_view()), name='hotfix-create'),
]

prd/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import datetime
import logging
from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _
from django.core.cache import cache
from simple_history.models import HistoricalRecords
from acm.models import Institution
from prd.api import GitLab, JiraProject
from celery import shared_task

# Get an instance of a logger
logger = logging.getLogger(__name__)

PART_TYPE = (
    ('sql', 'Database part'),
    ('java', 'Java part for application server'),
    ('standalone', 'Standalone module - java/c/c++'),
)


def getkey(item):
    return item[1]


def gitlab_project_list():
    short_list = cache.get('gitlab_project_list')
    if not short_list:
        project_list = GitLab().project_list()
        short_list = ((x.id, x.name_with_namespace) for x in project_list)
        short_list = sorted(short_list, key=getkey)
        cache.set('gitlab_project_list', short_list, 60 * 60)
    return short_list


def gitlab_project(pid):
    obj = GitLab().get_project(pid)
    if obj:
        return obj
    else:
        return None


@shared_task
def create_jira_version(project, version, released=True, desc=None):
    jira = JiraProject(project=project)

    if desc:
        version_desc = desc
    else:
        version_desc = 'New version {}'.format(version)
    jira.create_version(version_name=version, released=released, description=version_desc)


def check_jira_release(project, release):
    jira = JiraProject(project=project)
    task_name = 'Release {}'.format(release)
    issue = jira.search_issue(task_name)
    if not issue:
        issue = create_jira_release(project, release)
    return issue.key


def create_zero_tag(product, release, tag, author):
    # TODO add sql OR
    desc = "Zero tag for new release {}".format(release)
    release_module = ReleasePart.objects.filter(product__jira=product, release=release)
    if not release_module:
        release_module = ReleasePart.objects.filter(product__jira=product)
    for rec in release_module:
        revision = GitLab().create_tag(project_id=rec.gitlab_id, tag=tag, ref=release.dev_branch, user=author.username,
                                       desc=desc, ref_type='branch')
        if revision:
            build = Build.objects.get(release=release, name='0')
            build_revision = BuildRevision(release_part=rec, revision=revision, build=build)
            build_revision.save()


def check_jira_build(project, release, build):
    jira = JiraProject(project=project)
    build_name = 'Build {bld}'.format(bld=build)
    logger.debug("Check Jira build {bld} subtask in project {prj}".format(bld=build, prj=project))
    issue = jira.search_issue(build_name)
    if not issue:
        logger.debug("Task not found!")
        issue = create_jira_build(project, release, build)
    else:
        logger.debug("Task found!")
    return issue.key


def check_jira_task_status(task):
    jira = JiraProject(None)
    return jira.get_task_status(task)


def create_jira_release(project, release):
    jira = JiraProject(project=project)
    logger.info("Create Jira release task for project {}.".format(project))
    release_task = jira.create_release_task(release)
    return release_task


def create_jira_build(project, release, build):
    jira = JiraProject(project=project)
    release_task = check_jira_release(project, release)
    logger.info("Create new Jira Sub-task for build {}".format(build))
    build_task = jira.create_sub_task(release_task, build)
    return build_task


def jira_project_list(project=None):
    project_list_lov = cache.get('jira_project_list')
    if not project_list_lov:
        logger.info("Update Jira project list")
        project_list = JiraProject(project=project).project_list()
        project_list_lov = []
        for rec in ((x.key, "{name}({key})".format(name=x.name, key=x.key)) for x in project_list):
            # todo skip used projects
            project_list_lov.append(rec)
        cache.set('jira_project_list', project_list_lov, 60 * 60)  # cache one hour
    return project_list_lov


class Product(models.Model):
    title = models.CharField("Product title", max_length=200, unique=True)
    desc = models.CharField("Product Description", max_length=200, null=True, blank=True)
    wiki_url = models.URLField("Wiki/Confluence URL", null=True, blank=True)
    jira = models.CharField(_("Jira project code"), max_length=20, choices=jira_project_list(), unique=True,
                            help_text="Jira project key")
    system_name = models.CharField(_("Product system name"), max_length=20, unique=True)
    inst = models.ForeignKey(Institution, verbose_name='Group')
    owner = models.ForeignKey(User)
    created = models.DateField(auto_now_add=True)
    updated = models.DateField(auto_now=True)
    specification_repo = models.IntegerField(_("Specifications repository"), null=True, blank=True,
                                             help_text="Gitlab repository for product specifications",
                                             choices=gitlab_project_list())
    history = HistoricalRecords()

    def __str__(self):
        return "{title}: {inst}".format(title=self.title, inst=self.inst)

    def get_absolute_url(self):
        return reverse('product-detail', kwargs={'pk': self.pk})

    @property
    def name(self):
        return self.jira.lower()

    @property
    def wiki_url_link(self):
        if self.wiki_url:
            res = '<a href="{url}" targer="_blank">{url}</a>'.format(url=self.wiki_url)
        else:
            res = ''
        return res

    @property
    def jira_url_link(self):
        if self.jira:
            res = '<a href="{url}projects/{jira}" target="_blank">{jira}</a>'.format(jira=self.jira,
                                                                                     url=settings.JIRA_URL)
        else:
            res = ''
        return res

    @property
    def gitlab_project_url(self):
        return gitlab_project(self.specification_repo).web_url

    def save(self, *args, **kwargs):
        if not self.pk:
            if self.jira and not self.desc:
                self.desc = JiraProject(self.jira).get_project_desc()
        super(Product, self).save(*args, **kwargs)


class Release(models.Model):
    name = models.CharField(_("Release number"), max_length=20)
    product = models.ForeignKey(Product)
    jira = models.CharField(_("Jira task for release"), max_length=20, blank=True, null=True)
    is_active = models.BooleanField(_("Is active"), default=True)
    released = models.BooleanField(_("Is released"), default=False)
    author = models.ForeignKey(User)
    date_released = models.DateTimeField(_("Release date"), null=True, blank=True)
    created = models.DateTimeField(_("Created"), auto_now_add=True)
    updated = models.DateTimeField(_("Updated"), auto_now=True)
    history = HistoricalRecords()

    class Meta:
        unique_together = ('name', 'product',)
        ordering = ['-created']

    def __str__(self):
        return "{rel} - {prd}".format(rel=self.name, prd=self.product)

    def get_absolute_url(self):
        return reverse('release-detail', kwargs={'pk': self.pk})

    @property
    def get_jira_url(self):
        if self.jira:
            res = '<a href="{url}/browse/{task}" target"_blank">{task}</a>' \
                .format(url=settings.JIRA_URL, task=self.jira)
        else:
            res = ''
        return res

    @property
    def jira_task_name(self):
        if self.jira:
            return 'Release {}'.format(self.name)
        else:
            return None

    @property
    def dev_branch(self):
        if self.released:
            ref_name = '{name}-develop'.format(name=self.name)
        else:
            ref_name = 'future'
        return ref_name

    @property
    def stable_branch(self):
        if self.released:
            ref_name = '{name}-master'.format(name=self.name)
        else:
            ref_name = 'future'
        return ref_name

    def save(self, *args, **kwargs):
        if not self.pk:
            create_jira_version.delay(project=self.product.jira, version=self.name)
            logger.info("Create Jira version: {}".format(self.name))

            if not self.jira:
                self.jira = check_jira_release(self.product.jira, self.name)
            super(Release, self).save(*args, **kwargs)
            bld0 = Build(name='0', release=self, author=self.author, released=True, date_released=datetime.date.today())
            bld0.save()
            bld1 = Build(name='1', release=self, author=self.author)
            bld1.save()
        else:
            super(Release, self).save(*args, **kwargs)


class Build(models.Model):
    name = models.CharField("Build number", max_length=20)
    release = models.ForeignKey(Release)
    jira = models.CharField(_("Jira subtask for build"), max_length=20, null=True, blank=True)
    is_active = models.BooleanField(_("Is active"), default=True)
    released = models.BooleanField(_("Is released"), default=False)
    author = models.ForeignKey(User)
    date_released = models.DateTimeField(_("Build date"), null=True, blank=True)
    created = models.DateField(_("Created"), auto_now_add=True)
    updated = models.DateField(_("Updated"), auto_now=True)
    history = HistoricalRecords()

    class Meta:
        unique_together = ('name', 'release',)
        ordering = ["-created"]

    def __str__(self):
        return "{prd} {rel}.{build}".format(rel=self.release.name, prd=self.release.product, build=self.name)

    def get_absolute_url(self):
        return reverse('build-detail', kwargs={'pk': self.pk})

    @property
    def full_name(self):
        return '{rel}.{bld}'.format(rel=self.release.name, bld=self.name)

    @property
    def git_name(self):
        return 'v' + self.full_name

prd/forms.py
from django import forms
from .models import Release, Product


class ReleaseForm(forms.Form):
    def __init__(self, product, *args, **kwargs):
        super(ReleaseForm, self).__init__(*args, **kwargs)
        self.fields['release'] = forms.ChoiceField(
            choices=[(o.id, str(o)) for o in Release.objects.filter(product=product)]
        )
        self.fields['product'] = forms.IntegerField(initial=product.pk)
        self.fields['product'].widget = forms.HiddenInput()


class ProductForm(forms.ModelForm):
    # def __init__(self, *args, **kwargs):
    #     super(ProductForm, self).__init__(*args, **kwargs)
    #     lst_all = jira_project_list()
    #     lst_used = Product.objects.values_list('jira', flat=True)
    #     choose = [(x[0], "{name}".format(name=x[1], key=x[0])) for x in lst_all if x[0] not in lst_used]
    #     choose.insert(0, ('', '----'))
    #
    #     self.fields['jira'] = forms.ChoiceField(choices=choose, initial=self.initial['jira'])

    class Meta:
        model = Product
        fields = ['title', 'wiki_url', 'specification_repo', 'jira', 'inst', 'owner']

prd/templates/prd/build_detail.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% block title %}:Build detail {{ object.title }}{% endblock %}
{% block header %}{{ object.title }}{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="{% url 'build-list' %}" class="btn btn-success active" role="button">Back to build
                        list</a>
                </div>
            </div>
            <table class="table table-responsive table-bordered">
                <tr align="center" class="bg-warning">
                    <th colspan="3" class="bg-success">Build info</th>
                </tr>
                <tr>
                    <th colspan="2">Name</th>
                    <td>{{ object.full_name }}</td>
                </tr>
                <tr>
                    <th colspan="2">Release</th>
                    <td>{{ object.release_name }}</td>
                </tr>
            </table>
        </div>
    </div>
{% endblock %}

prd/templates/prd/build_list.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% block title %}:Build list{% endblock %}
{% block header %}Build list{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="{% url 'release-list-by-product' release.product.jira %}" class="btn btn-success active" role="button">Back to release
                        list</a>
                    <a href="{% url 'product-detail' release.product.pk %}" class="btn btn-success" role="button">{{ release.product.title }}</a>
                </div>
            </div>
            <div class="table-responsive">
                {% for rec in object_list %}
                    {% if forloop.first %}
                        <table class="table">
                        <thead>
                        <tr>
                            <th>Action</th>
                            <th>Name</th>
                            <th>Build Jira Task</th>
                            <th>Release Date</th>
                            <th>Author</th>
                        </tr>
                        </thead>
                    {% endif %}
                <tr {% if rec.released %}class="success"{% endif %}>
                    <td>{% if rec.released %}
                        {% if perms.prd.add_hotfix and rec.name != '0' %}
                            <a href="{% url 'hotfix-create' rec.pk %}" class="btn btn-success btn-sm"
                               role="button">{% bootstrap_icon 'plus' %}Issue hotfix</a>
                            {% elif rec.name == '0' %}
                            Technical build
                        {% endif %}
                    {% else %}
                        {% if perms.prd.add_build %}
                            <a href="{% url 'build-create' product.name %}?build={{ rec.pk }}" class="btn btn-primary btn-sm"
                               role="button">{% bootstrap_icon 'plus' %}Issue build</a>
                        {% endif %}
                    {% endif %}
                    <td>{{ rec.full_name }}</td>
                    <td>{{ rec.get_jira_url|safe }} </td>
                    <td>{% if rec.date_released %}
                        {{ rec.date_released|date }}
                    {% else %}

                    {% endif %}</td>
                    <td>{{ rec.author.get_full_name }}</td>
                </tr>
                {% if rec.hotfix_list %}
                    {% for hotfix in rec.hotfix_list %}
                        {% if forloop.first %}
                            <thead>
                            <tr>
                                <th>&nbsp;</th>
                                <th>Hotfix name</th>
                                <th>HotFix Jira task</th>
                                <th>Release Date</th>
                                <th>Author</th>
                            </tr>
                            </thead>
                        {% endif %}
                        <tr>
                            <td>&nbsp;</td>
                            <td>{{ hotfix.full_name }}</td>
                            <td>{{ hotfix.get_jira_url|safe }}</td>
                            <td>{{ hotfix.date_released|date }}</td>
                            <td>{{ hotfix.author.get_full_name }}</td>
                        </tr>
                    {% endfor %}
                {% endif %}

                {% if forloop.last %}
                    </table>
                {% endif %}
                {% empty %}
                    <p>No builds yet.</p>
                    </div>
                {% endfor %}
        </div>
    </div>
{% endblock %}

prd/templates/prd/process_create_build.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% block title %}:Run job {% endblock %}
{% block header %}Run job for create build {{ current_build.full_name }}.{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="list-group">
                <a href="#" class="list-group-item active">
                    <h4 class="list-group-item-heading">Release build</h4>
                    <p class="list-group-item-text">Issue build {{ current_build.full_name }}.</p>
                </a>
            </div>
             <div class="list-group">
                <a href="#" class="list-group-item">
                    <h4 class="list-group-item-heading">Create new build</h4>
                    <p class="list-group-item-text">Create new develop build {{ new_build.full_name }}.</p>
                </a>
            </div>
            <div class="list-group">
                <a href="#" class="list-group-item">
                    <h4 class="list-group-item-heading">Create new tag in Gitlab {{ current_build.git_name }} </h4>
                    <p class="list-group-item-text">Gitlab currently disabled.</p>
                </a>
            </div>
            <div class="list-group">
                <a href="#" class="list-group-item">
                    <h4 class="list-group-item-heading">Create new dictionary report
                        for {{ current_build.git_name }} </h4>
                    <p class="list-group-item-text">Dictionary report currently disabled.</p>
                </a>
            </div>
                        <div class="list-group">
                <a href="#" class="list-group-item">
                    <h4 class="list-group-item-heading">Run packaging
                        for {{ current_build.git_name }} </h4>
                    <p class="list-group-item-text">Packaging currently disabled</p>
                </a>
            </div>
        </div>
    </div>
{% endblock %}

prd/templates/prd/product_detail.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% block title %}:Product detail {{ object.title }}{% endblock %}
{% block header %}{{ object.title }}{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="panel panel-default">
                <div class="panel-body">
                    {% if perms.prd.add_release %}
                        <a href="{% url 'release-create' object.name %}" class="btn btn-primary"
                           role="button">{% bootstrap_icon 'plus' %}Add new release</a>
                    {% endif %}
                    <a href="{% url 'product-list' %}" class="btn btn-success active" role="button">Back to product
                        list</a>
                </div>
            </div>
            <table class="table table-responsive table-bordered">
                <tr align="center" class="bg-warning">
                    <th colspan="6" class="bg-success">Product info</th>
                </tr>
                {% if object.desc %}
                    <tr>
                        <th colspan="2">Description</th>
                        <td colspan="4">{{ object.desc }}</td>
                    </tr>
                {% endif %}
                <tr>
                    <th colspan="2">WIKI</th>
                    <td colspan="4">{{ object.wiki_url_link|safe }}</td>
                </tr>
                <tr>
                    <th colspan="2">Jira</th>
                    <td colspan="4">{{ object.jira_url_link|safe }}</td>
                </tr>
                {% if object.specification_repo %}
                    <tr>
                        <th colspan="2">Specification repository</th>
                        <td colspan="4">{{ object.gitlab_project_url|urlize }}</td>
                    </tr>
                {% endif %}
                <tr>
                    <th colspan="2">Release list</th>
                    <td colspan="4"><a href="{% url 'release-list-by-product' object.name %}">Release list</a></td>
                </tr>

                {% for rec in release_part %}
                    {% if forloop.first %}
                        <tr align="center">
                            <th colspan="5" class="bg-success">Product modules</th>
                            <td>
                                {% buttons %}
                                    <a href="{% url 'releasepart-create' object.pk %}" class="btn btn-primary"
                                       role="button">{% bootstrap_icon 'plus' %}Add new module</a>
                                {% endbuttons %}
                            </td>
                        </tr>
                        <tr>
                            <th>Module name</th>
                            <th>Module description</th>
                            <th>Gitlab project URL</th>
                            <th colspan="2" class="text-center">Module actions</th>
                        </tr>

                    {% endif %}
                    <tr>
                        <td>{{ rec.name }}</td>
                        <td>{{ rec.gitlab_project_desc }}</td>
                        <td>{{ rec.gitlab_project_url|urlize }}</td>
                        <td align="center">
                            {% if perms.prd.change_releasepart %}
                                {% buttons %}<a href="{% url 'releasepart-update' rec.pk %}"
                                                class="btn btn-warning btn-sm">{% bootstrap_icon "edit" %}Edit</a>
                                {% endbuttons %}
                            {% else %}
                                &nbsp;
                            {% endif %}
                        </td>
                        <td align="center">
                            {% if perms.prd.delete_releasepart %}
                                {% buttons %}<a href="{% url 'releasepart-delete' rec.pk %}"
                                                class="btn btn-danger btn-sm">{% bootstrap_icon "remove" %}Delete</a>
                                {% endbuttons %}

                            {% endif %}
                        </td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan="4">There are no modules in this product.
                            {% if perms.prd.add_releasepart %}
                                {% buttons %}
                                    <a href="{% url 'releasepart-create' object.pk %}" class="btn btn-primary"
                                       role="button">{% bootstrap_icon 'plus' %}Create module</a>
                                {% endbuttons %}
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>
{% endblock %}

prd/templates/prd/product_list.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% block title %}:Product list{% endblock %}
{% block header %}Product list{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            {% if perms.prd.add_product %}
                <div class="panel panel-default">
                    <div class="panel-footer">
                        {% buttons %}
                            <a href="{% url 'product-create' %}" class="btn btn-primary"
                               role="button">{% bootstrap_icon 'plus' %}Add new product</a>
                        {% endbuttons %}
                    </div>
                </div>
            {% endif %}
            <div class="table-responsive">
                {% for rec in object_list %}
                    {% if forloop.first %}
                        <table class="table table-bordered">
                        <tr>
                            <th>Title</th>
                            <th>Description</th>
                            <th>Wiki</th>
                            <th>Jira Project</th>
                            <th>Group</th>
                            <th>Owner</th>
                            <th>Releases</th>
                            <th colspan="2" align="center">Actions</th>
                        </tr>
                    {% endif %}
                <tr {% if rec.is_active %}class="success"{% endif %}>
                    <td><a href="{% url 'product-detail' rec.pk %}">{{ rec.title }}</a></td>
                    <td>{% if rec.desc %}{{ rec.desc }}{% else %} {% endif %}</td>
                    <td>{{ rec.wiki_url_link|safe }}</td>
                    <td>{{ rec.jira_url_link|safe }}</td>
                    <td>{{ rec.inst }}</td>
                    <td>{{ rec.owner.get_full_name }}</td>
                    <td><a href="{% url 'release-list-by-product' rec.name %}">Release list</a></td>
                    <td>{% if perms.prd.change_product %}
                        {% buttons %}<a href="{% url 'product-update' rec.pk %}"
                                        class="btn btn-warning btn-sm">{% bootstrap_icon "edit" %}Edit</a>
                        {% endbuttons %}
                    {% endif %}
                    </td>
                    <td>
                        {% if perms.prd.delete_product %}
                            {% buttons %}<a href="{% url 'product-delete' rec.pk %}"
                                            class="btn btn-danger btn-sm">{% bootstrap_icon "remove" %}Delete</a>
                            {% endbuttons %}
                        {% endif %}
                    </td>
                </tr>
                {% if forloop.last %}
                    </table>
                {% endif %}
                {% empty %}
                    <p>No releases yet.</p>
                    </div>
                {% endfor %}
        </div>
    </div>
{% endblock %}

prd/templates/prd/release_list.html
{% extends 'base.html' %}
{% load bootstrap3 %}\
{% load static %}
{% block title %}:Release list{% endblock %}
{% block header %}Release list{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="panel panel-default">
                <div class="panel-body">
                    {% if perms.prd.add_release %}
                        <a href="{% url 'release-create' product.name %}" class="btn btn-primary"
                           role="button">{% bootstrap_icon 'plus' %}Add new release</a>
                    {% endif %}
					{% if request.GET.filter %}
						<a href="{% url  'release-list-by-product' product.name %}" class="btn btn-info" role="button">Only active releases</a>
					{% else %}
						<a href="{% url  'release-list-by-product' product.name %}?filter=all" class="btn btn-info" role="button">All releases</a>
					{% endif %}
                    <a href="{% url 'product-list' %}" class="btn btn-success active" role="button">Back to product
                        list</a>
                </div>
            </div>
            <div class="table table-responsive">
                {% for release in object_list %}

                    {% if forloop.first %}
                        <table class="table table-bordered">
                        <tr>
                            <th>Name</th>
                            <th>Product</th>
                            <th>Jira</th>
                            <th>Release Date</th>
                            <th>Build List</th>
                            <th>Active</th>
                            <th>Issue release</th>
                        </tr>
                    {% endif %}
                <tr {% if release.is_active and release.released %}class="info"
                    {% elif not release.released %}class="warning"{% endif %}>
                    <td><a href="{% url 'build-list-by-release' release.pk %}" title="Build list">{{ release.name }}</a>
                    </td>
                    <td>{{ release.product }}</td>
                    <td>{{ release.get_jira_url|safe }} </td>
                    <td>{{ release.date_released|date }}</td>
                    <td><a href="{% url 'build-list-by-release' release.pk %}">Builds list</a></td>
                    <td>{% if release.is_active %}
                        <img src="{% static "img/ico/icon-yes.svg" %}">
                    {% else %}
                        <img src="{% static "img/ico/icon-no.svg" %}">
                    {% endif %}</td>
                    <td>{% if not release.released and perms.prd.add_release %}
                        <a href="{% url 'release-issue' release.pk %}" class="btn btn-success btn-sm"
                               role="button">{% bootstrap_icon 'plus' %}Issue release</a>{% endif %}</td>
                </tr>
                {% if forloop.last %}
                    </table>
                {% endif %}
                {% empty %}
                    <p>No releases yet.</p>
                    </div>
                {% endfor %}
        </div>
    </div>
{% endblock %}