acm/urls.py
from . import views
from django.conf.urls import url

urlpatterns = [
    # Product
    url(r'^admins/$', views.AdminList.as_view(), name='admin-list'),
]

rpt/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^jira-filter-list$', views.JiraFilterList.as_view(), name='jira-filter-list'),
    url(r'^jira-filter-detail/(?P<pk>[0-9]+)/$', views.JiraFilterDetail.as_view(), name='jira-filter-detail'),
    url(r'^jira-filter-add/$', views.create_filter, name='jira-filter-add'),
    url(r'^jira-filter-modify/(?P<pk>[0-9]+)/$', views.JiraFilterModify.as_view(), name='jira-filter-modify'),
    url(r'^jira-filter-delete/(?P<pk>[0-9]+)/$', views.JiraFilterDelete.as_view(), name='jira-filter-delete'),
    url(r'^jira-filter-download/(?P<filter_id>[0-9]+)/$', views.download_excel, name='download-excel'),
    url(r'^jira-filter-email/(?P<filter_id>[0-9]+)/$', views.email_excel, name='email-excel'),

]

rpt/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User
from django.db import models
from django.conf import settings

INTERVAL_CHOICE = [
    (0, 'Every work day'),
    (1, 'On Monday'),
    (2, 'On Friday'),
]


class JiraFilter(models.Model):
    empl = models.ForeignKey(User)
    jira_filter = models.IntegerField(_("Jira  filter"))
    interval = models.IntegerField(_("Interval"), null=True, blank=True, choices=INTERVAL_CHOICE)
    jql = models.CharField(_("JQL jira query"), max_length=2000, null=True, blank=True)

    @property
    def jira_url(self):
        return '{jira}/issues/?filter={id}'.format(jira=settings.JIRA_URL, id=self.jira_filter)

    def __str__(self):
        return '{empl} :: {filter}'.format(empl=self.empl, filter=self.jira_filter)


class JiraReportField(models.Model):
    jira_filter = models.ForeignKey(JiraFilter)
    order = models.PositiveSmallIntegerField(_("Field order"))
    field_name = models.CharField(_("Field name"), max_length=200)

rpt/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import logging

from django.conf import settings
from django.contrib import messages
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView, UpdateView, DeleteView
from .models import JiraFilter, INTERVAL_CHOICE
from prd.api import JiraProject
from django import forms
from django.contrib.auth.decorators import login_required
from rpt.api import excel_by_filter
from django.core.mail import send_mail, EmailMessage

logger = logging.getLogger(__name__)


class JiraFilterForm(forms.Form):
    jira_filter = forms.ChoiceField(choices=[], label='Jira filter')
    interval = forms.ChoiceField(choices=INTERVAL_CHOICE, label='Send interval')


@login_required
def create_filter(request):
    if request.method == "GET":
        form = JiraFilterForm()
        jira_list = JiraProject(user=request.user.username, password=request.session["secret"]).get_favorive_filter()
        jira_choice = [('-1', '---------')]
        jira_used_list = JiraFilter.objects.filter(empl=request.user).values_list('jira_filter')
        jira_choice.extend([(x.id, x.name) for x in jira_list if x.id not in jira_used_list])
        form.fields['jira_filter'].choices = jira_choice
    elif request.method == "POST":
        filter_id = request.POST['jira_filter']
        jira = JiraProject(user=request.user.username, password=request.session["secret"]).get_jira()
        flt = jira.filter(filter_id)
        jf = JiraFilter(empl=request.user, jira_filter=filter_id, interval=request.POST['interval'])
        jf.jql = flt.jql
        jf.save()
        return HttpResponseRedirect(reverse('jira-filter-list'))

    return render(request, 'jirafilter_form.html', locals())


class JiraFilterList(ListView):
    model = JiraFilter
    template_name = 'jirafilter_list.html'

    def get_queryset(self):
        self.user = self.request.user
        return JiraFilter.objects.filter(empl=self.user)

    def get_context_data(self, **kwargs):
        context = super(JiraFilterList, self).get_context_data(**kwargs)
        jira_list = JiraProject(user=self.request.user.username,
                                password=self.request.session["secret"]).get_favorive_filter()
        context['jira_list'] = [(int(x.id), x.name) for x in jira_list]

        return context


class JiraFilterDetail(DetailView):
    model = JiraFilter


class JiraFilterModify(UpdateView):
    model = JiraFilter


class JiraFilterDelete(DeleteView):
    model = JiraFilter
    template_name = 'jirafilter_confirm_delete.html'
    success_url = reverse_lazy('jira-filter-list')


def download_excel(request, filter_id):
    filename = excel_by_filter(filter_id=filter_id, user=request.user, passwd=request.session["secret"])
    response = HttpResponse(file(filename))
    response['Content-Type'] = 'application/vnd.ms-excel'
    response['Content-Disposition'] = 'attachment; filename=%s' % filename.split('/')[-1]
    return response


def email_excel(request, filter_id):
    filename = excel_by_filter(filter_id=filter_id, user=request.user, passwd=request.session["secret"])
    subject = 'Jira report by filter {}'.format(filter_id)
    text = 'See attach.'
    mail = EmailMessage(subject, text, settings.DEFAULT_FROM_EMAIL, [request.user.email, ])
    mail.content_subtype = "html"
    mail.attach_file(filename)
    mail.send()
    messages.add_message(request, messages.SUCCESS, 'Email to {} was send!'.format(request.user.email))
    return HttpResponseRedirect(reverse_lazy('jira-filter-list'))

rpt/templates/jirafilter_confirm_delete.html
{% extends 'base.html' %}
{% block title %}{{object_name}} Confirm delete?{% endblock %}
{% block content %}
    <div id="content-container" class="container p-none">
        <div class="side-p">
            <h3>Are you sure?</h3>
            <p>You're about to delete Jira Filter {{ object }}. Please confirm.</p>
            <form action="" method="post">
                {% csrf_token %}
                <input class="btn btn-link"
                       type="button" value="Cancel"
                       onclick="window.history.go(-1);"/>
                <input class="btn btn-danger" type="submit" value="Confirm"/>
            </form>
        </div>
    </div>
{% endblock %}

rpt/templates/jirafilter_form.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% block title %}:Jira filter management{% endblock %}
{% block header %}Jira filter management{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="{% url 'jira-filter-list' %}" class="btn btn-success active" role="button">Back to Jira
                        filter list</a>
                </div>
            </div>
            <form action="" method="post" class="form">{% csrf_token %}
                {% bootstrap_form form %}
                {% buttons %}
                    <button type="submit" class="btn btn-primary">
                        {% bootstrap_icon "star" %} Submit
                    </button>
                {% endbuttons %}
            </form>
        </div>
    </div>
{% endblock %}

rpt/templates/jirafilter_list.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% block title %}:Jira task list filters{% endblock %}
{% block header %}Jira task list filters{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="panel panel-default">
                <div class="panel-body">
                    {% if perms.rpt.add_jirafilter %}
                        <a href="{% url 'jira-filter-add' %}" class="btn btn-primary"
                           role="button">{% bootstrap_icon 'plus' %}Add new Jira Filter</a>
                    {% endif %}
                </div>
            </div>
            <div class="table-responsive">
                {% for rec in object_list %}
                    {% if forloop.first %}
                        <table class="table">
                        <thead>
                        <tr>
                            <th>Action</th>
                            <th>Jira Filter</th>
                            <th>Interval</th>
                            <th>Download</th>
                            <th>Send email</th>
                        </tr>
                        </thead>
                    {% endif %}
                    <tr>
                        <td>|
                            <a href="{% url 'jira-filter-delete' rec.pk %}">Remove</a> |
                        </td>
                        <td>{% for rec2 in jira_list %}{% if rec2.0 == rec.jira_filter %}<a href="{{ rec.jira_url|safe }}">{{ rec2.1 }}({{ rec2.0 }})</a>{% endif %}{% endfor %}</td>
                        <td>{{ rec.get_interval_display }}</td>
                        <td><a href="{% url 'download-excel' rec.jira_filter %}">Download</a></td>
                        <td><a href="{% url 'email-excel' rec.jira_filter %}">Send</a></td>

                    </tr>
                {% empty %}
                    Not yet saved Jira Filters
                {% endfor %}
                </table>
            </div>
        </div>
    </div>
{% endblock %}