acm/urls.py
from . import views
from django.conf.urls import url

urlpatterns = [
    # Product
    url(r'^admins/$', views.AdminList.as_view(), name='admin-list'),
]

envrnmnt/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    # DBInstances
    url(r'^dbinstance-list$', views.DBInstanceList.as_view(), name='dbinstance-list'),
    url(r'^dbinstance-detail/(?P<pk>[0-9]+)/$', views.DBInstanceDetail.as_view(), name='dbinstance-detail'),
    url(r'^dbinstance-add/$', views.CreateDBInstance.as_view(), name='dbinstance-create'),
    url(r'^dbinstance-update/(?P<pk>[0-9]+)/$', views.UpdateDBInstance.as_view(), name='dbinstance-update'),
    url(r'^dbinstance-delete/(?P<pk>[0-9]+)/$', views.DeleteDBInstance.as_view(), name='dbinstance-delete'),

    #   WEBInstances
    url(r'^webinstance-list$', views.WEBInstanceList.as_view(), name='webinstance-list'),
    url(r'^webinstance-detail/(?P<pk>[0-9]+)/$', views.WEBInstanceDetail.as_view(), name='webinstance-detail'),
    url(r'^webinstance-add/$', views.CreateWEBInstance.as_view(), name='webinstance-create'),
    url(r'^webinstance-update/(?P<pk>[0-9]+)/$', views.UpdateWEBInstance.as_view(), name='webinstance-update'),
    url(r'^webinstance-delete/(?P<pk>[0-9]+)/$', views.DeleteWEBInstance.as_view(), name='webinstance-delete'),

    #   STLNInstances
    url(r'^stlninstance-list$', views.STLNInstanceList.as_view(), name='stlninstance-list'),
    url(r'^stlninstance-detail/(?P<pk>[0-9]+)/$', views.STLNInstanceDetail.as_view(), name='stlninstance-detail'),
    url(r'^stlninstance-add/$', views.CreateSTLNInstance.as_view(), name='stlninstance-create'),
    url(r'^stlninstance-update/(?P<pk>[0-9]+)/$', views.UpdateSTLNInstance.as_view(), name='stlninstance-update'),
    url(r'^stlninstance-delete/(?P<pk>[0-9]+)/$', views.DeleteSTLNInstance.as_view(), name='stlninstance-delete'),

    #   Environments
    url(r'^env-list$', views.EnvLint.as_view(), name='env-list'),
    url(r'^env-detail/(?P<pk>[0-9]+)/$', views.EnvDetail.as_view(), name='env-detail'),
    url(r'^env-add/$', views.CreateEnv, name='env-create'),
    url(r'^env-update/(?P<pk>[0-9]+)/$', views.UpdateEnv, name='env-update'),
    url(r'^env-delete/(?P<pk>[0-9]+)/$', views.DeleteEnv.as_view(), name='env-delete'),
]

envrnmnt/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.urls import reverse
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.fields import GenericRelation
from django.contrib.contenttypes.models import ContentType
from acm.models import Institution
from prd.models import ReleasePart

WEIGHT_ARR = (
    ('Big', 'For SmartVista project - 30 Gb'),
    ('Medium', 'For SMSGate, SSO projects - 5 Gb'),
    ('Small', 'For other project - less 1 Gb'),
)


class DBInstance(models.Model):
    host = models.CharField('Host', max_length=200)
    sid = models.CharField('SID', max_length=20, blank=True, null=True, default='SV')
    port = models.IntegerField('Port', default=1521)
    login = models.CharField('DB Login', max_length=200)
    passwd = models.CharField('DB Password', max_length=200)
    sys_user = models.CharField('System Login', max_length=200, blank=True, null=True, default='system')
    sys_passwd = models.CharField('System Password', max_length=200, blank=True, null=True, default='SYSTEM1')
    weight = models.CharField('Weight', choices=WEIGHT_ARR, max_length=200, )
    content_type = models.ForeignKey(ContentType, null=True, blank=True, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField(null=True, blank=True)
    content_object = GenericForeignKey('content_type', 'object_id')
    release_part = models.ForeignKey(ReleasePart, blank=True, null=True)

    def __str__(self):
        return '{host}::{login}'.format(host=self.host, login=self.login)

    def get_absolute_url(self):
        return reverse('dbinstance-detail', kwargs={'pk': self.pk})

    def get_fields(self):
        return [(field.verbose_name, field._get_val_from_obj(self)) for field in self.__class__._meta.fields]


class WEBInstance(models.Model):
    host = models.CharField('Host', max_length=200)
    port = models.IntegerField('Port', default=7001)
    target_server = models.CharField('Server', max_length=200)
    login = models.CharField('Login', max_length=200, default='weblogic')
    passwd = models.CharField('Password', max_length=200)
    content_type = models.ForeignKey(ContentType, null=True, blank=True, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField(null=True, blank=True)
    content_object = GenericForeignKey('content_type', 'object_id')
    release_part = models.ForeignKey(ReleasePart, blank=True, null=True)

    def __str__(self):
        return 't3://{host}:{port}'.format(host=self.host, port=self.port)

    def get_absolute_url(self):
        return reverse('webinstance-detail', kwargs={'pk': self.pk})

    def get_fields(self):
        return [(field.verbose_name, field._get_val_from_obj(self)) for field in self.__class__._meta.fields]


class STLNInstance(models.Model):
    host = models.CharField('Host', max_length=200)
    port = models.IntegerField('Port', default=22)
    user = models.CharField('User', max_length=200, default='svfe')
    passwd = models.CharField('Password', max_length=200)
    content_type = models.ForeignKey(ContentType, null=True, blank=True, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField(null=True, blank=True)
    content_object = GenericForeignKey('content_type', 'object_id')
    release_part = models.ForeignKey(ReleasePart, blank=True, null=True)

    def __str__(self):
        return '{user}@{host}'.format(host=self.host, user=self.user)

    def get_absolute_url(self):
        return reverse('stlninstance-detail', kwargs={'pk': self.pk})

    def get_fields(self):
        return [(field.verbose_name, field._get_val_from_obj(self)) for field in self.__class__._meta.fields]


class Environment(models.Model):
    name = models.CharField('Name', max_length=200, unique=True)
    is_active = models.BooleanField("Is active", default=True)
    dbinstances = GenericRelation(DBInstance)
    webinstances = GenericRelation(WEBInstance)
    stlninstances = GenericRelation(STLNInstance)
    inst = models.ForeignKey(Institution, verbose_name='Group')

    def __str__(self):
        return self.name

    def get_fields(self):
        return [(field.verbose_name, field._get_val_from_obj(self)) for field in self.__class__._meta.fields]

    def get_absolute_url(self):
        return reverse('env-detail', kwargs={'pk': self.pk})

envrnmnt/forms.py
from django.forms import ModelForm
from .models import *


class EnvForm(ModelForm):
    class Meta:
        model = Environment
        fields = ['name', 'is_active', 'inst']

envrnmnt/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from django.contrib.contenttypes.forms import generic_inlineformset_factory
from .models import *
from .forms import EnvForm
from django.shortcuts import render, HttpResponseRedirect, get_object_or_404
from django.contrib import messages


class EnvLint(ListView):
    model = Environment
    context_object_name = 'envs'


class EnvDetail(DetailView):
    model = Environment
    context_object_name = 'env'


class DeleteEnv(DeleteView):
    model = Environment
    success_url = reverse_lazy('env-list')
    success_message = 'Environment was deleted successfully.'
    template_name = "envrnmnt/instance_confirm_delete.html"

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super(DeleteEnv, self).delete(request, *args, **kwargs)


def CreateEnv(request):
    DBInstanceFormSet = generic_inlineformset_factory(DBInstance, extra=1, can_delete=True)
    WEBInstanceFormSet = generic_inlineformset_factory(WEBInstance, extra=1, can_delete=True)
    STLNInstanceFormSet = generic_inlineformset_factory(STLNInstance, extra=1, can_delete=True)

    if request.method == "POST":
        form = EnvForm(data=request.POST)
        if form.is_valid():
            c_env = form.save()
            formsetdb = DBInstanceFormSet(data=request.POST, instance=c_env)
            formsetweb = WEBInstanceFormSet(data=request.POST, instance=c_env)
            formsetstln = STLNInstanceFormSet(data=request.POST, instance=c_env)
            if formsetdb.is_valid() and formsetweb.is_valid() and formsetstln.is_valid():
                formsetdb.save()
                formsetweb.save()
                formsetstln.save()

                return HttpResponseRedirect('/instance/env-list')
    else:
        form = EnvForm()
        formsetdb = DBInstanceFormSet()
        formsetweb = WEBInstanceFormSet()
        formsetstln = STLNInstanceFormSet()
    return render(request, 'envrnmnt/environment_form.html', locals())


def UpdateEnv(request, pk):
    env = get_object_or_404(Environment, id=pk)
    DBInstanceFormSet = generic_inlineformset_factory(DBInstance, extra=0, can_delete=True)
    WEBInstanceFormSet = generic_inlineformset_factory(WEBInstance, extra=0, can_delete=True)
    STLNInstanceFormSet = generic_inlineformset_factory(STLNInstance, extra=0, can_delete=True)

    if request.method == "POST":
        form = EnvForm(data=request.POST, instance=env)
        formsetdb = DBInstanceFormSet(data=request.POST, instance=env)
        formsetweb = WEBInstanceFormSet(data=request.POST, instance=env)
        formsetstln = STLNInstanceFormSet(data=request.POST, instance=env)
        if form.is_valid():
            if formsetdb.is_valid() and formsetweb.is_valid() and formsetstln.is_valid():
                formsetdb.save()
                formsetweb.save()
                formsetstln.save()
                form.save()
                return HttpResponseRedirect('/instance/env-list')
    else:
        form = EnvForm(instance=env)
        formsetdb = DBInstanceFormSet(instance=env)
        formsetweb = WEBInstanceFormSet(instance=env)
        formsetstln = STLNInstanceFormSet(instance=env)
    return render(request, 'envrnmnt/environment_edit_form.html', locals())


class DBInstanceList(ListView):
    model = DBInstance


class DBInstanceDetail(DetailView):
    model = DBInstance
    template_name = "envrnmnt/instance_detail.html"

    def get_context_data(self, **kwargs):
        context = super(DetailView, self).get_context_data(**kwargs)
        context['list_url'] = "dbinstance-list"
        return context


class CreateDBInstance(CreateView):
    model = DBInstance
    fields = ['host', 'sid', 'port', 'login', 'passwd', 'sys_user', 'sys_passwd', 'weight']
    template_name = "envrnmnt/instance_form.html"

    def get_context_data(self, **kwargs):
        context = super(CreateView, self).get_context_data(**kwargs)
        context['list_url'] = "dbinstance-list"
        return context


class UpdateDBInstance(UpdateView):
    model = DBInstance
    fields = ['host', 'sid', 'port', 'login', 'passwd', 'sys_user', 'sys_passwd', 'weight']
    success_message = 'DB Instance was updated successfully.'
    template_name = "envrnmnt/instance_form.html"

    def form_valid(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super(UpdateDBInstance, self).form_valid(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(UpdateView, self).get_context_data(**kwargs)
        context['list_url'] = "dbinstance-list"
        return context


class DeleteDBInstance(DeleteView):
    model = DBInstance
    success_url = reverse_lazy('dbinstance-list')
    success_message = 'DB Instance was deleted successfully.'
    template_name = "envrnmnt/instance_confirm_delete.html"

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super(DeleteDBInstance, self).delete(request, *args, **kwargs)


class WEBInstanceList(ListView):
    model = WEBInstance


class WEBInstanceDetail(DetailView):
    model = WEBInstance
    template_name = "envrnmnt/instance_detail.html"

    def get_context_data(self, **kwargs):
        context = super(DetailView, self).get_context_data(**kwargs)
        context['list_url'] = "webinstance-list"
        return context


class CreateWEBInstance(CreateView):
    model = WEBInstance
    fields = ['host', 'port', 'target_server', 'login', 'passwd']
    template_name = "envrnmnt/instance_form.html"

    def get_context_data(self, **kwargs):
        context = super(CreateView, self).get_context_data(**kwargs)
        context['list_url'] = "webinstance-list"
        return context


class UpdateWEBInstance(UpdateView):
    model = WEBInstance
    fields = ['host', 'port', 'target_server', 'login', 'passwd']
    success_message = 'WEB Instance was updated successfully.'
    template_name = "envrnmnt/instance_form.html"

    def form_valid(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super(UpdateWEBInstance, self).form_valid(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(UpdateView, self).get_context_data(**kwargs)
        context['list_url'] = "webinstance-list"
        return context


class DeleteWEBInstance(DeleteView):
    model = WEBInstance
    success_url = reverse_lazy('webinstance-list')
    success_message = 'WEB Instance was deleted successfully.'
    template_name = "envrnmnt/instance_confirm_delete.html"

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super(DeleteWEBInstance, self).delete(request, *args, **kwargs)


class STLNInstanceList(ListView):
    model = STLNInstance


class STLNInstanceDetail(DetailView):
    model = STLNInstance
    template_name = "envrnmnt/instance_detail.html"

    def get_context_data(self, **kwargs):
        context = super(DetailView, self).get_context_data(**kwargs)
        context['list_url'] = "stlninstance-list"
        return context


class CreateSTLNInstance(CreateView):
    model = STLNInstance
    fields = ['host', 'port', 'user', 'passwd']
    template_name = "envrnmnt/instance_form.html"

    def get_context_data(self, **kwargs):
        context = super(CreateView, self).get_context_data(**kwargs)
        context['list_url'] = "stlninstance-list"
        return context


class UpdateSTLNInstance(UpdateView):
    model = STLNInstance
    fields = ['host', 'port', 'user', 'passwd']
    success_message = 'Standalone Instance was updated successfully.'
    template_name = "envrnmnt/instance_form.html"

    def form_valid(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super(UpdateSTLNInstance, self).form_valid(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(UpdateView, self).get_context_data(**kwargs)
        context['list_url'] = "stlninstance-list"
        return context


class DeleteSTLNInstance(DeleteView):
    model = STLNInstance
    success_url = reverse_lazy('stlninstance-list')
    success_message = 'Standalone Instance was deleted successfully.'
    template_name = "envrnmnt/instance_confirm_delete.html"

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super(DeleteSTLNInstance, self).delete(request, *args, **kwargs)

envrnmnt/templates/envrnmnt/dbinstance_list.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% block title %}:Instance list{% endblock %}
{% block header %}Instance list{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            {% if perms.envrnmnt.add_dbinstance %}
                <div class="panel panel-default">
                    <div class="panel-footer">
                        {% buttons %}
                            <a href="{% url 'dbinstance-create' %}" class="btn btn-primary"
                               role="button">{% bootstrap_icon 'plus' %} Add new DB Instance</a>
                        {% endbuttons %}
                    </div>
                </div>
            {% endif %}
            <div class="table-responsive">
                {% for rec in object_list %}
                    {% if forloop.first %}
                        <table class="table table-bordered">
                            <tr>
                                <th>Host</th>
                                <th>Login</th>
                                <th>Password</th>
                                <th>Port</th>
                                <th>SID</th>
                                <th>Weight</th>
                                {% if perms.envrnmnt.change_dbinstance %}
                                    <th>Edit</th>
                                {% endif %}
                                {% if perms.envrnmnt.delete_dbinstance %}
                                    <th>Delete</th>
                                {% endif %}
                            </tr>
                    {% endif %}
                            <tr>
                                <td><a href="{% url 'dbinstance-detail' rec.pk %}">{{ rec.host }}</a></td>
                                <td>{{ rec.login}}</td>
                                <td>{{ rec.passwd }}</td>
                                <td>{{ rec.port}}</td>
                                <td>{{ rec.sid }}</td>
                                <td>{{ rec.weight}}</td>
                                    {% if perms.envrnmnt.change_dbinstance %}
                                        <td>
                                            {% buttons %}
                                                <a href="{% url 'dbinstance-update' rec.pk %}"
                                                   class="btn btn-warning btn-sm">{% bootstrap_icon "edit" %}
                                                </a>
                                            {% endbuttons %}
                                        </td>
                                    {% endif %}
                                    {% if perms.envrnmnt.delete_dbinstance %}
                                        <td>
                                            {% buttons %}
                                                <a href="{% url 'dbinstance-delete' rec.pk %}"
                                                   class="btn btn-warning btn-sm">{% bootstrap_icon "remove" %}
                                                </a>
                                            {% endbuttons %}
                                        </td>
                                    {% endif %}

                            </tr>
                    {% if forloop.last %}
                        </table>
                    {% endif %}
                {% empty %}
                    <p>No Instance yet.</p>
                    </div>
                {% endfor %}
        </div>
    </div>
{% endblock %}

envrnmnt/templates/envrnmnt/environment_list.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% block title %}:List of Environments{% endblock %}
{% block header %}List of Environments:{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            {% if perms.envrnmnt.add_stlninstance %}
                <div class="panel panel-default">
                    <div class="panel-footer">
                        {% buttons %}
                            <a href="{% url 'env-create' %}" class="btn btn-primary"
                               role="button">{% bootstrap_icon 'plus' %} Add new Environment</a>
                        {% endbuttons %}
                    </div>
                </div>
            {% endif %}
            <div class="table-responsive">
                {% for rec in object_list %}
                    {% if forloop.first %}
                        <table class="table table-bordered">
                            <tr>
                                <th>Name</th>
                                <th>Active</th>
                                <th>Oracle DB Instance</th>
                                <th>Weblogic Instance</th>
                                <th>Standalone Instance</th>
                                {% if perms.envrnmnt.change_environment %}
                                    <th>Edit</th>
                                {% endif %}
                                {% if perms.envrnmnt.delete_environment%}
                                    <th>Delete</th>
                                {% endif %}
                            </tr>
                    {% endif %}
                            <tr {% if rec.is_active == False %} style="color:#d3d3d3;" {% endif %}>
                                <td><a href="{% url 'env-detail' rec.pk %}">{{ rec.name }}</a></td>
                                <td>{{ rec.is_active}}</td>
                                <td>
                                    {% if rec.dbinstances.all %}
                                    {% for db in rec.dbinstances.all %}
                                        {{ db.login }}/{{ db.passwd }}@{{ db.host }}:{{ db.port }}/{{ db.sid }}</br>
                                    {% endfor %}
                                    {% else %}
                                     N/A
                                    {% endif %}
                                </td>
                                <td>
                                    {% if rec.webinstances.all %}
                                        {% for web in rec.webinstances.all %}
                                            t3://{{ web.host }}:{{ web.port }} </br>
                                        {% endfor %}
                                    {% else %}
                                        N/A
                                    {% endif %}
                                </td>
                                <td>
                                    {% if rec.stlninstances.all %}
                                        {% for st in rec.stlninstances.all %}
                                            {{ st.user }}@{{ st.host }} </br>
                                        {% endfor %}
                                    {% else %}
                                        N/A
                                    {% endif %}
                                </td>
                                {% if perms.envrnmnt.change_environment %}
                                    <td>
                                        {% buttons %}
                                            <a href="{% url 'env-update' rec.pk %}"
                                               class="btn btn-warning btn-sm">{% bootstrap_icon "edit" %}
                                            </a>
                                        {% endbuttons %}
                                    </td>
                                {% endif %}
                                {% if perms.envrnmnt.delete_environment %}
                                    <td>
                                        {% buttons %}
                                            <a href="{% url 'env-delete' rec.pk %}"
                                               class="btn btn-danger btn-sm">{% bootstrap_icon "remove" %}
                                            </a>
                                        {% endbuttons %}
                                    </td>
                                {% endif %}

                            </tr>
                    {% if forloop.last %}
                        </table>
                    {% endif %}
                {% empty %}
                    <p>No Instance yet.</p>
                    </div>
                {% endfor %}
        </div>
    </div>
{% endblock %}

envrnmnt/templates/envrnmnt/instance_confirm_delete.html
{% extends 'base.html' %}
{% block title %}{{object_name}} Confirm delete?{% endblock %}
{% block content %}
    <div id="content-container" class="container p-none">
        <div class="side-p">
            <h3>Are you sure?</h3>
            <p>You're about to delete Instance {{ object }}. Please confirm.</p>
            <form action="" method="post">
                {% csrf_token %}
                <input class="btn btn-link"
                       type="button" value="Cancel"
                       onclick="window.history.go(-1);"/>
                <input class="btn btn-danger" type="submit" value="Confirm"/>
            </form>
        </div>
    </div>
{% endblock %}

envrnmnt/templates/envrnmnt/stlninstance_list.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% block title %}:Instance list{% endblock %}
{% block header %}Instance list{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            {% if perms.envrnmnt.add_stlninstance %}
                <div class="panel panel-default">
                    <div class="panel-footer">
                        {% buttons %}
                            <a href="{% url 'stlninstance-create' %}" class="btn btn-primary"
                               role="button">{% bootstrap_icon 'plus' %} Add new Standalone Instance</a>
                        {% endbuttons %}
                    </div>
                </div>
            {% endif %}
            <div class="table-responsive">
                {% for rec in object_list %}
                    {% if forloop.first %}
                        <table class="table table-bordered">
                            <tr>
                                <th>Host</th>
                                <th>Port</th>
                                <th>User</th>
                                <th>Password</th>
                                {% if perms.envrnmnt.change_stlninstance %}
                                    <th>Edit</th>
                                {% endif %}
                                {% if perms.envrnmnt.delete_stlninstance %}
                                    <th>Delete</th>
                                {% endif %}
                            </tr>
                    {% endif %}
                            <tr>
                                <td><a href="{% url 'stlninstance-detail' rec.pk %}">{{ rec.host }}</a></td>
                                <td>{{ rec.port}}</td>
                                <td>{{ rec.user}}</td>
                                <td>{{ rec.passwd}}</td>
                                {% if perms.envrnmnt.change_stlninstance %}
                                    <td>
                                        {% buttons %}
                                            <a href="{% url 'stlninstance-update' rec.pk %}"
                                               class="btn btn-warning btn-sm">{% bootstrap_icon "edit" %}
                                            </a>
                                        {% endbuttons %}
                                    </td>
                                {% endif %}
                                {% if perms.envrnmnt.delete_stlninstance %}
                                    <td>
                                        {% buttons %}
                                            <a href="{% url 'stlninstance-delete' rec.pk %}"
                                               class="btn btn-warning btn-sm">{% bootstrap_icon "remove" %}
                                            </a>
                                        {% endbuttons %}
                                    </td>
                                {% endif %}

                            </tr>
                    {% if forloop.last %}
                        </table>
                    {% endif %}
                {% empty %}
                    <p>No Instance yet.</p>
                    </div>
                {% endfor %}
        </div>
    </div>
{% endblock %}

envrnmnt/templates/envrnmnt/webinstance_list.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% block title %}:Instance list{% endblock %}
{% block header %}Instance list{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            {% if perms.envrnmnt.add_webinstance %}
                <div class="panel panel-default">
                    <div class="panel-footer">
                        {% buttons %}
                            <a href="{% url 'webinstance-create' %}" class="btn btn-primary"
                               role="button">{% bootstrap_icon 'plus' %} Add new Web Instance</a>
                        {% endbuttons %}
                    </div>
                </div>
            {% endif %}
            <div class="table-responsive">
                {% for rec in object_list %}
                    {% if forloop.first %}
                        <table class="table table-bordered">
                            <tr>
                                <th>Host</th>
                                <th>Port</th>
                                <th>Managed Server</th>
                                <th>Login</th>
                                <th>Password</th>
                                {% if perms.envrnmnt.change_webinstance %}
                                    <th>Edit</th>
                                {% endif %}
                                {% if perms.envrnmnt.delete_webinstance %}
                                    <th>Delete</th>
                                {% endif %}
                            </tr>
                    {% endif %}
                            <tr>
                                <td><a href="{% url 'webinstance-detail' rec.pk %}">{{ rec.host }}</a></td>
                                <td>{{ rec.port}}</td>
                                <td>{{ rec.target_server }}</td>
                                <td>{{ rec.login}}</td>
                                <td>{{ rec.passwd}}</td>
                                    {% if perms.envrnmnt.change_webinstance %}
                                        <td>
                                            {% buttons %}
                                                <a href="{% url 'webinstance-update' rec.pk %}"
                                                   class="btn btn-warning btn-sm">{% bootstrap_icon "edit" %}
                                                </a>
                                            {% endbuttons %}
                                        </td>
                                    {% endif %}
                                    {% if perms.envrnmnt.delete_webinstance %}
                                        <td>
                                            {% buttons %}
                                                <a href="{% url 'webinstance-delete' rec.pk %}"
                                                   class="btn btn-warning btn-sm">{% bootstrap_icon "remove" %}
                                                </a>
                                            {% endbuttons %}
                                        </td>
                                    {% endif %}

                            </tr>
                    {% if forloop.last %}
                        </table>
                    {% endif %}
                {% empty %}
                    <p>No Instance yet.</p>
                    </div>
                {% endfor %}
        </div>
    </div>
{% endblock %}